defmodule Goatmire.Repo.Migrations.InitBlog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add :author_id,
          references(:authors, column: :id, name: "posts_author_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :body, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:authors, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:authors)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `posts` table without the `posts_author_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:posts)
  end
end